name: Publish Release
on:
  push:
    tags:
      - '^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jungwinter/split@v2
      id: split
      with:
        msg: ${{ github.ref }}
        separator: '/'

    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        title: ${{ steps.split.outputs._2}}