name: Publish Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: jungwinter/split@v2
      id: split
      with:
        msg: ${{ github.ref }}
        separator: '/'

    # - uses: actions/checkout@v3
    - name: Create Release
      uses: zendesk/action-create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.split.outputs._2}}
        release_name: ${{ steps.split.outputs._2}}
        draft: false
        prerelease: false
        generate_release_notes: true